import "./globals.css"; // Ensure this imports your updated globals.css
import Header from "./components/Header";
import Footer from "./components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-white text-gray-900"> 
         <Header className="bg-slate-900 text-gray-400"/>
        <main className="bg-slate-950 text-gray-400 ">{children}</main>
      </body>
    </html>
  );
}
